spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qq@982709437
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=true&characterEncoding=utf8
  # 修改数据时更改请求为put
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml

server:
  port: 8080
